### ISSUE TITLE
Crash when file is already open

### ISSUE THREAD

**Issue by Octavelscx** [L-A-Marchetti/BOMulus#19]
It appears that the application crashes when attempting to compare Excel files that are already open in another application (Microsoft Excel in my case)

**Comment by L-A-Marchetti** [comment]
I think it could be an idea to copy temporary the file before open it to fix that.

**Comment by Octavelscx** [comment]
Yes, and for integrity reasons, it's better to work on a copy (even a temporary one) of the file 🙃

**Comment by L-A-Marchetti** [comment]
ofc I already made the function for the export option so I'll just have to use it for the file preparation.

**Comment by L-A-Marchetti** [comment]
- Temporary files are now created in the os tmp directory before open them, and then deleted automatically.
