### ISSUE TITLE
Analysis Report

### ISSUE THREAD

**Issue by L-A-Marchetti** [L-A-Marchetti/BOMulus#36]
The idea is to have access to the analysis report after all API requests have been made. It should contains:

- If some components were not found propose some not 100% matching manufacturer parts numbers.
- Show out of stock components.
- Show warnings on risky life cycle status.
- Show suspicious mismatches like values, description etc.
- Show suspicious same values from different manufacturers. (to unify)
- Show total price and price diff.
- Show manufacturers important messages, product compliance and restrictions.

Every ideas are welcome, the fact that you can apply some suggested changes to the new BOM will be on a different branch later.

**Comment by Octavelscx** [comment]
I think some of theses ideas might be splitted in parts : 

**Informations updating/precising :** 

- If some components were not found propose some not 100% matching manufacturer parts numbers.
- Show suspicious mismatches like values, description etc.
- Show total price and price diff

**Ordering/Manufacturing :** 

- Show out of stock components.
- Show warnings on risky life cycle status.
- Show manufacturers important messages, product compliance and restrictions.

**Smart suggestions :** 

- Show suspicious similar values from different manufacturers in specific component categories.
- Highlight usage of different part sizes in same component categories.

**Comment by L-A-Marchetti** [comment]
- Components detection reset after analysis fixed.
- Report Analysis with basic infos completed.
- Out of stock components implemented.
- Risky life cycle status implemented.
- Manufacturer important messages implemented.
- Min price, max price and diff price implemented.
- Mismatching manufacturer part number implemented with suggestions.
- Mismatching descriptions implemented.
- GLib corrupted double-linked list detected fixed.

All smart suggestions will come after the completion of #39 in another branch.
