### ISSUE TITLE
Column Header Row Specification

### ISSUE THREAD

**Issue by Octavelscx** [L-A-Marchetti/BOMulus#5]
Enhancement suggestion : 
Add the ability to specify the row containing the column headers to retrieve their names for display. This would allow users to correctly identify column names even if the headers are not on the first row.

**Comment by L-A-Marchetti** [comment]
Why not propose an automatic heading by searching for specific keywords like "designator," "quantity," etc.? With the possibility to adjust in the options if necessary?

Does Altium inject metadata to help? Like #Quantity #Designator?

**Comment by L-A-Marchetti** [comment]
- Spin button to increment the header line implemented.
- Columns in the result view now take the defined header names.
