### ISSUE TITLE
Export Options

### ISSUE THREAD

**Issue by Octavelscx** [L-A-Marchetti/BOMulus#8]
Enhancement suggestion : 
Add functionality to export the diff results in PDF and EXCEL formats. This would provide users with more flexibility in how they save and share diff data.

**Comment by L-A-Marchetti** [comment]
- New button to export file.
- Destination path can be selected using a chooser.
- A name can be entered.
- You can select which diff you want to display in the exported file (insert, delete, update)
- Export is using the same template of both old and new version BOMs.
- If you decide to display delete lines will be inserted to show them, same for updates. (a future option will let you choose to insert or not newlines for the updates)
- Some messages are handled like undefined path and name and export success.
- This feature still need to be tested on windows.
