### ISSUE TITLE
Filtered Sorting

### ISSUE THREAD

**Issue by Octavelscx** [L-A-Marchetti/BOMulus#9]
Enhancement suggestions : 
Introduce filtered sorting options to display only updates, inserts, or deletes. This would allow users to focus on specific types of changes and improve data analysis.

**Comment by L-A-Marchetti** [comment]
- Multi diff generation bug fixed.
- Table reset fixed.
- Filters to display or not EQUAL, DELETE, INSERT and UPDATE fully implemented.
